language: python

python:
  - 3.5

env:
  global:
- secure: "A3eJDMPJjSx4b4qCfAEUPwv5snoXyUkpHKAh9rrsKvlKxmHPrR8NjCwbpWqX2xBN69UBLhPR8gVAXs6SUblhJnhMx9MPzMx4ceGBT3fzUfQmqDGXpkQxqn6UiK2UtCuG0lQjuS3t39/n1fPC7YJ7wSdGK6m2eCooOCKlW8stNy+yc98H7sV5XZPKuGTwQKvDCaaoAE5OE1jz8BQdCAOh1+0Zh829AcGCQZiXmRicvQtCbFJCQLAcaNh0f9zTtaPtyuIq5oSLiaF5KZegLDIde+oi5Vz3RaXtBdTEv5Z+h8WbANHqNFX73dKOken5I4DPvl5SAnTrxjds659Re13EAZfsCiwP7qljke0jv+zqsRFxfnWYpgp/R0pqCkPtdEHi2nsSTX6eMZS+k/jLl0m7n1BTIui5wrdvu5cVX5KkcUDXdCYxyGZ+wBvs0KyuoKlxiLC8Lo2IXGj2eD6hLlPqoHYdWWGNCmqAw0kJ8lRWAajuDkIEpqjcsVVJPc+L2JxfupU6vezqUhaFFrrBbVJFFVSM9xH0Mg/kOG6FCJBJUH96YPZlFiYty6QEuZt5pMXigFJLNq3WlAPXxQLAKEVILBCBkQR4SWIWIbWo014/ZUkxCQhOrMbRC/wzDzDnoGxFGTd7TmMbn0m3QC/Ro8fhpRid/7m5qqnYGH0IITD/Qro="

install:
  - pip install sphinx

script: make html -C _build/

after_success:
  - ./build_current.sh
